name: Hello Automation World

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:

    runs-on: macos-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Check directory
        run: | 
          ls -a
          
      - name: Run tests
        run: mvn "-Dtest=APITests,UITests,UnitTests" test
